Support new dataset "biaobei" BZNSYP High quality single speaker for …
babysor/MockingBird pull request #72
Opened 2021-09-01 15:48 UTC by babysor

…Chinese

2021-09-28 11:16 UTC, Jaromhar requested changes

2021-09-28 14:40 UTC, babysor commented on README.md
> +Allowing parameter `--dataset {dataset}` to support adatatang_200zh, magicdata, aishell3, BZNSYP
This change has been deprecated since it distroy your model when you use this dataset. :<

2021-09-28 14:40 UTC, closed without merging

2021-10-16 02:44 UTC, babysor commented
> 有支持biaobei标贝数据集的正确版本吧。最好整合到主版本里面去。

因为biaobei是单人语音 导致模型不可用 所以不打算整合

2021-10-16 02:50 UTC, lcp580 commented
那么，单独支持标贝数据集，可行不？此分支已有的可以如何改进呢？