Temp to support Mozilla Common Voice dataset
babysor/MockingBird pull request #75
Opened 2021-09-05 13:45 UTC by FawenYo

You **HAVE TO** rename Mozilla Common Voice to the below data structure

- {dataset_name}/
- - zh-TW/
- - - clips/
- - - - xxx.mp3
- - - xxx.tsv

* TODO: Currently only support `train.tsv`, will also support other data like `test.tsv` or `validate.tsv` in the future
* TODO: Fix "no wordS" error when processing Mozilla Common Voice (cause only `train.tsv` for now)

2021-09-07 04:39 UTC, babysor requested changes

2021-09-07 04:39 UTC, babysor commented on synthesizer/preprocess.py
> +    is_tsv = False
tsv不是一个很好的区别信号，参考我的biaobei里的commit，这里需要针对不同数据集增加新的transcript处理 方法、

2021-09-07 04:39 UTC, babysor commented on synthesizer/preprocess_speaker.py
> -    wav_fpath_list = speaker_dir.glob("*.wav")
参考biaobei commit

2021-12-15 15:03 UTC, GITHUBGUY12357999 commented
I will resolve these problems I will et back to you in this.

2021-12-15 15:04 UTC, GITHUBGUY12357999 requested changes
need changes

2022-01-04 06:53 UTC, GITHUBGUY12357999 commented
These many fixes are required. 

Please fix them. 


Thank You.

2022-01-10 06:03 UTC, freddy123098 requested changes
requesting changes.

2022-01-13 11:27 UTC, freddy123098 commented on synthesizer/preprocess.py
> +    is_tsv = False
So can u push the line in red to the above line thank you @FawenYo.

2022-01-13 11:28 UTC, freddy123098 commented on synthesizer/preprocess_speaker.py
> -    wav_fpath_list = speaker_dir.glob("*.wav")
Same with this one also.

2023-05-06 06:36 UTC, closed without merging